/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DurationTimeController;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class main extends javax.swing.JFrame {

    private String nameFile;
    private String directory;
    private final DurationTimeController controller;
    private final FileTypeFilter type = new FileTypeFilter(".csv", "Comma Separated Values File");
    private final JFileChooser chooser = new JFileChooser();
    private final String origin = "-6.8746025,107.6024968";
    private final String sampel1 = "-6.9536001,107.6193958";//amaya residence
    private final String sampel2 = "-6.937021,107.6643817";//puspa utara

    /**
     * Creates new form main
     */
    public main() {
        this.controller = new DurationTimeController();
        chooser.setFileFilter(type);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        trafficModelLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        originLabel = new javax.swing.JLabel();
        bestGuessCheckBox = new javax.swing.JCheckBox();
        optimistCheckBox = new javax.swing.JCheckBox();
        pessimistCheckBox = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        sampel1RadioButton = new javax.swing.JRadioButton();
        sampel2RadioButton = new javax.swing.JRadioButton();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        datePicker.getEditor().setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Analisis Waktu Bandung");
        setResizable(false);

        trafficModelLabel.setText("Traffic Model    :");

        dateLabel.setText("Date                 :");

        originLabel.setText("Origin               : ");

        bestGuessCheckBox.setText("best_guess");

        optimistCheckBox.setText("optimistic");

        pessimistCheckBox.setText("pessimistic");

        saveButton.setText("Save to CSV & Show");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(sampel1RadioButton);
        sampel1RadioButton.setText("Sampel 1 : Amaya Residence");

        buttonGroup1.add(sampel2RadioButton);
        sampel2RadioButton.setText("Sampel 2 : Jln. Puspa Utara");

        datePicker.setFormats("dd MM yyyy");
        datePicker.setLinkDay(new Date());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(originLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sampel2RadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sampel1RadioButton, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saveButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(trafficModelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bestGuessCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(optimistCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pessimistCheckBox))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originLabel)
                    .addComponent(sampel1RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampel2RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trafficModelLabel)
                    .addComponent(optimistCheckBox)
                    .addComponent(pessimistCheckBox)
                    .addComponent(bestGuessCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            if (!datePicker.getEditor().getText().equals("")) {
                Calendar calendar = new GregorianCalendar();
                calendar.setTime(datePicker.getDate());
                long temp = calendar.getTime().getTime() - datePicker.getLinkDay().getTime();
                if (calendar.get(Calendar.DAY_OF_WEEK) != 2) {
                    System.out.println(calendar.get(Calendar.DAY_OF_WEEK));
                    JOptionPane.showMessageDialog(this, "Tanggal yang anda pilih bukan hari senin", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (temp <= 0) {
                        JOptionPane.showMessageDialog(this, "Tanggal yang anda masukan adalah masa lampau atau hari ini, Pilihlah tanggal yang akan datang", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (sampel1RadioButton.isSelected()) {
                            if (bestGuessCheckBox.isSelected()) {
                                if (optimistCheckBox.isSelected()) {
                                    if (pessimistCheckBox.isSelected()) {
                                        controller.doCalculate(datePicker.getEditor(), origin, sampel1, bestGuessCheckBox, optimistCheckBox, pessimistCheckBox);
                                        int result = chooser.showSaveDialog(this);
                                        if (result == JFileChooser.APPROVE_OPTION) {
                                            Desktop dt = Desktop.getDesktop();
                                            nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                            directory = chooser.getCurrentDirectory().toString();
                                            controller.saveData(directory, nameFile);
                                            File file = new File(directory + "\\" + nameFile);
                                            dt.open(file);
                                        }
                                    } else {
                                        controller.doCalculate(datePicker.getEditor(), origin, sampel1, bestGuessCheckBox, optimistCheckBox, null);
                                        int result = chooser.showSaveDialog(this);
                                        if (result == JFileChooser.APPROVE_OPTION) {
                                            Desktop dt = Desktop.getDesktop();
                                            nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                            directory = chooser.getCurrentDirectory().toString();
                                            controller.saveData(directory, nameFile);
                                            File file = new File(directory + "\\" + nameFile);
                                            dt.open(file);
                                        }
                                    }
                                } else if (pessimistCheckBox.isSelected()) {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel1, bestGuessCheckBox, pessimistCheckBox, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                } else {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel1, bestGuessCheckBox, null, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                }
                            } else if (optimistCheckBox.isSelected()) {
                                if (pessimistCheckBox.isSelected()) {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel1, optimistCheckBox, pessimistCheckBox, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                } else {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel1, optimistCheckBox, null, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                }
                            } else if (pessimistCheckBox.isSelected()) {
                                controller.doCalculate(datePicker.getEditor(), origin, sampel1, pessimistCheckBox, null, null);
                                int result = chooser.showSaveDialog(this);
                                if (result == JFileChooser.APPROVE_OPTION) {
                                    Desktop dt = Desktop.getDesktop();
                                    nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                    directory = chooser.getCurrentDirectory().toString();
                                    controller.saveData(directory, nameFile);
                                    File file = new File(directory + "\\" + nameFile);
                                    dt.open(file);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Anda harus memilih minimal salah satu dari 3 traffic model yang telah disediakan", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                        } else if (sampel2RadioButton.isSelected()) {
                            if (bestGuessCheckBox.isSelected()) {
                                if (optimistCheckBox.isSelected()) {
                                    if (pessimistCheckBox.isSelected()) {
                                        controller.doCalculate(datePicker.getEditor(), origin, sampel2, bestGuessCheckBox, optimistCheckBox, pessimistCheckBox);
                                        int result = chooser.showSaveDialog(this);
                                        if (result == JFileChooser.APPROVE_OPTION) {
                                            Desktop dt = Desktop.getDesktop();
                                            nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                            directory = chooser.getCurrentDirectory().toString();
                                            controller.saveData(directory, nameFile);
                                            File file = new File(directory + "\\" + nameFile);
                                            dt.open(file);
                                        }
                                    } else {
                                        controller.doCalculate(datePicker.getEditor(), origin, sampel2, bestGuessCheckBox, optimistCheckBox, null);
                                        int result = chooser.showSaveDialog(this);
                                        if (result == JFileChooser.APPROVE_OPTION) {
                                            Desktop dt = Desktop.getDesktop();
                                            nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                            directory = chooser.getCurrentDirectory().toString();
                                            controller.saveData(directory, nameFile);
                                            File file = new File(directory + "\\" + nameFile);
                                            dt.open(file);
                                        }
                                    }
                                } else if (pessimistCheckBox.isSelected()) {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel2, bestGuessCheckBox, pessimistCheckBox, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                } else {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel2, bestGuessCheckBox, null, null);

                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                }
                            } else if (optimistCheckBox.isSelected()) {
                                if (pessimistCheckBox.isSelected()) {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel2, optimistCheckBox, pessimistCheckBox, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                } else {
                                    controller.doCalculate(datePicker.getEditor(), origin, sampel2, optimistCheckBox, null, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        dt.open(file);
                                    }
                                }
                            } else if (pessimistCheckBox.isSelected()) {
                                controller.doCalculate(datePicker.getEditor(), origin, sampel2, pessimistCheckBox, null, null);
                                int result = chooser.showSaveDialog(this);
                                if (result == JFileChooser.APPROVE_OPTION) {
                                    Desktop dt = Desktop.getDesktop();
                                    nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                    directory = chooser.getCurrentDirectory().toString();
                                    controller.saveData(directory, nameFile);
                                    File file = new File(directory + "\\" + nameFile);
                                    dt.open(file);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Harus pilih minimal salah satu dari 3", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Harus pilih antara sampel 1 atau sampel 2", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilihlah tanggal", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException | IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bestGuessCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dateLabel;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JCheckBox optimistCheckBox;
    private javax.swing.JLabel originLabel;
    private javax.swing.JCheckBox pessimistCheckBox;
    private javax.swing.JRadioButton sampel1RadioButton;
    private javax.swing.JRadioButton sampel2RadioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel trafficModelLabel;
    // End of variables declaration//GEN-END:variables
}
