/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DurationTimeController;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.PlainDocument;

/**
 *
 * @author LENOVO
 */
public class main extends javax.swing.JFrame {

    private String nameFile;
    private String directory;
    private final DurationTimeController controller;
    private final FileTypeFilter type = new FileTypeFilter(".csv", "Comma Separated Values File");
    private final JFileChooser chooser = new JFileChooser();
    private String origin = "";
    private String destination = "";
    private final DocFilter docFilter = new DocFilter();

    public main() {
        this.controller = new DurationTimeController();
        chooser.setFileFilter(type);
        initComponents();
        PlainDocument doc1 = (PlainDocument) oloTextField.getDocument();
        PlainDocument doc2 = (PlainDocument) olaTextField.getDocument();
        PlainDocument doc3 = (PlainDocument) dloTextField.getDocument();
        PlainDocument doc4 = (PlainDocument) dlaTextField.getDocument();
        doc1.setDocumentFilter(docFilter);
        doc2.setDocumentFilter(docFilter);
        doc3.setDocumentFilter(docFilter);
        doc4.setDocumentFilter(docFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        trafficModelLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        originLabel = new javax.swing.JLabel();
        bestGuessCheckBox = new javax.swing.JCheckBox();
        optimistCheckBox = new javax.swing.JCheckBox();
        pessimistCheckBox = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        datePicker.getEditor().setEditable(false);
        endDateLabel = new javax.swing.JLabel();
        endDatePicker = new org.jdesktop.swingx.JXDatePicker();
        destinationLabel = new javax.swing.JLabel();
        originLongLabel = new javax.swing.JLabel();
        originLatLabel = new javax.swing.JLabel();
        destinationLongLabel = new javax.swing.JLabel();
        destinationLatLabel = new javax.swing.JLabel();
        oloTextField = new javax.swing.JTextField();
        olaTextField = new javax.swing.JTextField();
        dloTextField = new javax.swing.JTextField();
        dlaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Analisis Waktu Bandung");
        setResizable(false);

        trafficModelLabel.setText("Traffic Model    :");

        startDateLabel.setText("Start Date        :");

        originLabel.setText("Origin               :");

        bestGuessCheckBox.setText("best_guess");

        optimistCheckBox.setText("optimistic");

        pessimistCheckBox.setText("pessimistic");

        saveButton.setText("Save to CSV & Show");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        datePicker.setFormats("dd MM yyyy");
        datePicker.setLinkDay(new Date());
        datePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerActionPerformed(evt);
            }
        });

        endDateLabel.setText("End Date         :");

        endDatePicker.setEditable(false);
        endDatePicker.setFormats("dd MM yyyy");

        destinationLabel.setText("Destination      :");

        originLongLabel.setText("Long :");

        originLatLabel.setText("Lat :");

        destinationLongLabel.setText("Long :");

        destinationLatLabel.setText("Lat :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trafficModelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bestGuessCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optimistCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pessimistCheckBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(destinationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinationLatLabel)
                            .addComponent(destinationLongLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dloTextField)
                            .addComponent(dlaTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(originLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(originLatLabel)
                            .addComponent(originLongLabel))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oloTextField)
                            .addComponent(olaTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originLongLabel)
                    .addComponent(oloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originLatLabel)
                    .addComponent(olaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel)
                    .addComponent(destinationLongLabel)
                    .addComponent(dloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLatLabel)
                    .addComponent(dlaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateLabel)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trafficModelLabel)
                    .addComponent(optimistCheckBox)
                    .addComponent(pessimistCheckBox)
                    .addComponent(bestGuessCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            if (!datePicker.getEditor().getText().equals("")) {
                Calendar calendar = new GregorianCalendar();
                calendar.setTime(datePicker.getDate());
                long temp = calendar.getTime().getTime() - datePicker.getLinkDay().getTime();
                if (calendar.get(Calendar.DAY_OF_WEEK) != 2) {
                    System.out.println(calendar.get(Calendar.DAY_OF_WEEK));
                    JOptionPane.showMessageDialog(this, "Tanggal yang anda pilih bukan hari senin, silahkan pilih tanggal yang merupakan hari senin", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (temp <= 0) {
                        JOptionPane.showMessageDialog(this, "Tanggal yang anda masukan adalah masa lampau atau hari ini, silahkan pilihlah tanggal yang akan datang", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (oloTextField.getText().equals("") && oloTextField.getText().equals("") && dloTextField.getText().equals("") && dloTextField.getText().equals("")) {
                            JOptionPane.showMessageDialog(this, "Silahkan masukan titik koordinat pada origin dan destination", "ERROR", JOptionPane.ERROR_MESSAGE);
                        } else {
                            this.origin = oloTextField.getText() + "," + oloTextField.getText().equals("");
                            this.destination = dloTextField.getText() + "," + dloTextField.getText().equals("");
                            if (bestGuessCheckBox.isSelected()) {
                                if (optimistCheckBox.isSelected()) {
                                    if (pessimistCheckBox.isSelected()) {
                                        controller.doCalculate(datePicker.getEditor(), origin, destination, bestGuessCheckBox, optimistCheckBox, pessimistCheckBox);
                                        int result = chooser.showSaveDialog(this);
                                        if (result == JFileChooser.APPROVE_OPTION) {
                                            Desktop dt = Desktop.getDesktop();
                                            nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                            directory = chooser.getCurrentDirectory().toString();
                                            controller.saveData(directory, nameFile);
                                            File file = new File(directory + "\\" + nameFile);
                                            JOptionPane.showMessageDialog(this, controller.getResult(), "Hasil", JOptionPane.INFORMATION_MESSAGE);
                                            dt.open(file);
                                        }
                                    } else {
                                        controller.doCalculate(datePicker.getEditor(), origin, destination, bestGuessCheckBox, optimistCheckBox, null);
                                        int result = chooser.showSaveDialog(this);
                                        if (result == JFileChooser.APPROVE_OPTION) {
                                            Desktop dt = Desktop.getDesktop();
                                            nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                            directory = chooser.getCurrentDirectory().toString();
                                            controller.saveData(directory, nameFile);
                                            File file = new File(directory + "\\" + nameFile);
                                            JOptionPane.showMessageDialog(this, controller.getResult(), "Hasil", JOptionPane.INFORMATION_MESSAGE);
                                            dt.open(file);
                                        }
                                    }
                                } else if (pessimistCheckBox.isSelected()) {
                                    controller.doCalculate(datePicker.getEditor(), origin, destination, bestGuessCheckBox, pessimistCheckBox, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        JOptionPane.showMessageDialog(this, controller.getResult(), "Hasil", JOptionPane.INFORMATION_MESSAGE);
                                        dt.open(file);
                                    }
                                } else {
                                    controller.doCalculate(datePicker.getEditor(), origin, destination, bestGuessCheckBox, null, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        JOptionPane.showMessageDialog(this, controller.getResult(), "Hasil", JOptionPane.INFORMATION_MESSAGE);
                                        dt.open(file);
                                    }
                                }
                            } else if (optimistCheckBox.isSelected()) {
                                if (pessimistCheckBox.isSelected()) {
                                    controller.doCalculate(datePicker.getEditor(), origin, destination, optimistCheckBox, pessimistCheckBox, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        JOptionPane.showMessageDialog(this, controller.getResult(), "Hasil", JOptionPane.INFORMATION_MESSAGE);
                                        dt.open(file);
                                    }
                                } else {
                                    controller.doCalculate(datePicker.getEditor(), origin, destination, optimistCheckBox, null, null);
                                    int result = chooser.showSaveDialog(this);
                                    if (result == JFileChooser.APPROVE_OPTION) {
                                        Desktop dt = Desktop.getDesktop();
                                        nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                        directory = chooser.getCurrentDirectory().toString();
                                        controller.saveData(directory, nameFile);
                                        File file = new File(directory + "\\" + nameFile);
                                        JOptionPane.showMessageDialog(this, controller.getResult(), "Hasil", JOptionPane.INFORMATION_MESSAGE);
                                        dt.open(file);
                                    }
                                }
                            } else if (pessimistCheckBox.isSelected()) {
                                controller.doCalculate(datePicker.getEditor(), origin, destination, pessimistCheckBox, null, null);
                                int result = chooser.showSaveDialog(this);
                                if (result == JFileChooser.APPROVE_OPTION) {
                                    Desktop dt = Desktop.getDesktop();
                                    nameFile = chooser.getSelectedFile().getName() + type.getExtension();
                                    directory = chooser.getCurrentDirectory().toString();
                                    controller.saveData(directory, nameFile);
                                    File file = new File(directory + "\\" + nameFile);
                                    JOptionPane.showMessageDialog(this, controller.getResult(), "Hasil", JOptionPane.INFORMATION_MESSAGE);
                                    dt.open(file);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Anda harus memilih minimal salah satu dari 3 traffic model yang telah disediakan", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Anda belum memilih tanggal, silahkan pilih tanggal", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException | IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void datePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerActionPerformed
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(datePicker.getDate());
        long temp = calendar.getTimeInMillis() + 518400000;
        calendar.setTimeInMillis(temp);
        endDatePicker.setDate(new Date(temp));

    }//GEN-LAST:event_datePickerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bestGuessCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel destinationLatLabel;
    private javax.swing.JLabel destinationLongLabel;
    private javax.swing.JTextField dlaTextField;
    private javax.swing.JTextField dloTextField;
    private javax.swing.JLabel endDateLabel;
    private org.jdesktop.swingx.JXDatePicker endDatePicker;
    private javax.swing.JTextField olaTextField;
    private javax.swing.JTextField oloTextField;
    private javax.swing.JCheckBox optimistCheckBox;
    private javax.swing.JLabel originLabel;
    private javax.swing.JLabel originLatLabel;
    private javax.swing.JLabel originLongLabel;
    private javax.swing.JCheckBox pessimistCheckBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel trafficModelLabel;
    // End of variables declaration//GEN-END:variables
}
